[2025-09-04T12:19:50.056+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-09-04T12:19:50.066+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: generated_py_do_something.my_function manual__2025-09-04T12:19:49.117924+00:00 [queued]>
[2025-09-04T12:19:50.069+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: generated_py_do_something.my_function manual__2025-09-04T12:19:49.117924+00:00 [queued]>
[2025-09-04T12:19:50.069+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 4
[2025-09-04T12:19:50.074+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): my_function> on 2025-09-04 12:19:49.117924+00:00
[2025-09-04T12:19:50.076+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=71) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-09-04T12:19:50.077+0000] {standard_task_runner.py:63} INFO - Started process 72 to run task
[2025-09-04T12:19:50.077+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'generated_py_do_something', 'my_function', 'manual__2025-09-04T12:19:49.117924+00:00', '--job-id', '73', '--raw', '--subdir', 'DAGS_FOLDER/dag_do_something.py', '--cfg-path', '/tmp/tmp33vxf44_']
[2025-09-04T12:19:50.078+0000] {standard_task_runner.py:91} INFO - Job 73: Subtask my_function
[2025-09-04T12:19:50.097+0000] {task_command.py:426} INFO - Running <TaskInstance: generated_py_do_something.my_function manual__2025-09-04T12:19:49.117924+00:00 [running]> on host ade5f5069171
[2025-09-04T12:19:50.127+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='data_team' AIRFLOW_CTX_DAG_ID='generated_py_do_something' AIRFLOW_CTX_TASK_ID='my_function' AIRFLOW_CTX_EXECUTION_DATE='2025-09-04T12:19:49.117924+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-09-04T12:19:49.117924+00:00'
[2025-09-04T12:19:50.128+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-09-04T12:19:50.141+0000] {logging_mixin.py:188} INFO - Doing something inside AirFlow!
[2025-09-04T12:19:50.141+0000] {logging_mixin.py:188} INFO - Step: 0
[2025-09-04T12:19:50.141+0000] {logging_mixin.py:188} INFO - No data!
[2025-09-04T12:19:50.141+0000] {logging_mixin.py:188} INFO - Step: 2
[2025-09-04T12:19:50.141+0000] {logging_mixin.py:188} INFO - No data!
[2025-09-04T12:19:50.141+0000] {logging_mixin.py:188} INFO - Step: 4
[2025-09-04T12:19:50.141+0000] {logging_mixin.py:188} INFO - No data!
[2025-09-04T12:19:50.141+0000] {logging_mixin.py:188} INFO - Step: 6
[2025-09-04T12:19:50.141+0000] {logging_mixin.py:188} INFO - No data!
[2025-09-04T12:19:50.142+0000] {logging_mixin.py:188} INFO - Step: 8
[2025-09-04T12:19:50.142+0000] {logging_mixin.py:188} INFO - No data!
[2025-09-04T12:19:50.142+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-09-04T12:19:50.142+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-09-04T12:19:50.146+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=generated_py_do_something, task_id=my_function, run_id=manual__2025-09-04T12:19:49.117924+00:00, execution_date=20250904T121949, start_date=20250904T121950, end_date=20250904T121950
[2025-09-04T12:19:50.176+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-09-04T12:19:50.183+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-09-04T12:19:50.184+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
