[2025-08-16T13:35:17.810+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-08-16T13:35:17.819+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: generated_py_do_something.run_python_function manual__2025-08-16T13:35:16.748215+00:00 [queued]>
[2025-08-16T13:35:17.821+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: generated_py_do_something.run_python_function manual__2025-08-16T13:35:16.748215+00:00 [queued]>
[2025-08-16T13:35:17.821+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-08-16T13:35:17.825+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): run_python_function> on 2025-08-16 13:35:16.748215+00:00
[2025-08-16T13:35:17.828+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=58) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-08-16T13:35:17.828+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'generated_py_do_something', 'run_python_function', 'manual__2025-08-16T13:35:16.748215+00:00', '--job-id', '35', '--raw', '--subdir', 'DAGS_FOLDER/generated_py_do_something.py', '--cfg-path', '/tmp/tmp013p4now']
[2025-08-16T13:35:17.829+0000] {standard_task_runner.py:91} INFO - Job 35: Subtask run_python_function
[2025-08-16T13:35:17.829+0000] {standard_task_runner.py:63} INFO - Started process 59 to run task
[2025-08-16T13:35:17.852+0000] {task_command.py:426} INFO - Running <TaskInstance: generated_py_do_something.run_python_function manual__2025-08-16T13:35:16.748215+00:00 [running]> on host 1ed929767bb5
[2025-08-16T13:35:17.881+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='generated_py_do_something' AIRFLOW_CTX_TASK_ID='run_python_function' AIRFLOW_CTX_EXECUTION_DATE='2025-08-16T13:35:16.748215+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-08-16T13:35:16.748215+00:00'
[2025-08-16T13:35:17.881+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-08-16T13:35:17.888+0000] {logging_mixin.py:188} INFO - Doing something inside AirFlow!
[2025-08-16T13:35:17.888+0000] {logging_mixin.py:188} INFO - Step: 0
[2025-08-16T13:35:17.888+0000] {logging_mixin.py:188} INFO - No data!
[2025-08-16T13:35:17.888+0000] {logging_mixin.py:188} INFO - Step: 2
[2025-08-16T13:35:17.888+0000] {logging_mixin.py:188} INFO - No data!
[2025-08-16T13:35:17.888+0000] {logging_mixin.py:188} INFO - Step: 4
[2025-08-16T13:35:17.889+0000] {logging_mixin.py:188} INFO - No data!
[2025-08-16T13:35:17.889+0000] {logging_mixin.py:188} INFO - Step: 6
[2025-08-16T13:35:17.889+0000] {logging_mixin.py:188} INFO - No data!
[2025-08-16T13:35:17.889+0000] {logging_mixin.py:188} INFO - Step: 8
[2025-08-16T13:35:17.889+0000] {logging_mixin.py:188} INFO - No data!
[2025-08-16T13:35:17.889+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-08-16T13:35:17.889+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-08-16T13:35:17.893+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=generated_py_do_something, task_id=run_python_function, run_id=manual__2025-08-16T13:35:16.748215+00:00, execution_date=20250816T133516, start_date=20250816T133517, end_date=20250816T133517
[2025-08-16T13:35:17.929+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-08-16T13:35:17.936+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-08-16T13:35:17.936+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
